spring:
    h2:
        console:
            enabled: true
            path: /h2
    datasource:
        url: jdbc:h2:mem:user
    data:
        jpa:
            repositories:
                bootstrap-mode: default

